In [ ]:
# import numpy as np
# from sklearn.cluster import KMeans

# # Define the colors as an array of RGB values
# colors = np.array([
#     (8, 52, 73),
#     (168, 198, 217),
#     (68, 115, 141),
#     (4, 21, 10),
#     (187, 186, 166),
#     (239, 239, 243),
#     (57, 77, 67),
#     (138, 170, 192),
#     (107, 145, 165),
#     (191, 212, 227),
#     (30, 48, 34),
#     (139, 144, 122),
#     (215, 210, 192),
#     (165, 167, 148),
#     (28, 85, 119),
#     (91, 108, 94)
# ])

# # Initialize KMeans with 3 clusters
# kmeans = KMeans(n_clusters=3, init=np.array([
#     (187, 186, 166),  # Centroid 1 (Color 5)
#     (107, 145, 165),  # Centroid 2 (Color 9)
#     (215, 210, 192)   # Centroid 3 (Color 13)
# ]), n_init=1, max_iter=100)

# # Fit the model to the color data
# kmeans.fit(colors)

# # Get the cluster centers (final centroids)
# centroids = kmeans.cluster_centers_

# # Print the results
# print("Final Centroids (RGB values):")
# for i, centroid in enumerate(centroids, start=1):
#     print(f"Centroid {i}: ({centroid[0]:.1f}, {centroid[1]:.1f}, {centroid[2]:.1f})")

In [14]:
import numpy as np
from sklearn.cluster import KMeans

# Step 1: Define the 16 colors (RGB values)
colors = {
    1: (8, 52, 73),
    2: (168, 198, 217),
    3: (68, 115, 141),
    4: (4, 21, 10),
    5: (187, 186, 166),
    6: (239, 239, 243),
    7: (57, 77, 67),
    8: (138, 170, 192),
    9: (107, 145, 165),
    10: (191, 212, 227),
    11: (30, 48, 34),
    12: (139, 144, 122),
    13: (215, 210, 192),
    14: (165, 167, 148),
    15: (28, 85, 119),
    16: (91, 108, 94)
}

# Convert colors to numpy array and normalize (0-1)
X = np.array(list(colors.values())) / 255.0

# Part (a): Initial centroids 5, 9, 13
initial_centroids_a = np.array([colors[5], colors[9], colors[13]]) / 255.0
kmeans_a = KMeans(n_clusters=3, init=initial_centroids_a, n_init=1, max_iter=1000)
kmeans_a.fit(X)
final_centroids_a = kmeans_a.cluster_centers_ * 255

# Part (b): Initial centroids 1, 2, 3
initial_centroids_b = np.array([colors[1], colors[2], colors[3]]) / 255.0
kmeans_b = KMeans(n_clusters=3, init=initial_centroids_b, n_init=1, max_iter=1000)
kmeans_b.fit(X)
final_centroids_b = kmeans_b.cluster_centers_ * 255

# Print results
print("Final Centroids (Part a):")
print(np.round(final_centroids_a, 1))
print("\nFinal Centroids (Part b):")
print(np.round(final_centroids_b, 1))
print("\nResults differ:", not np.allclose(final_centroids_a, final_centroids_b))

Final Centroids (Part a):
[[147.2 162.4 158.6]
 [ 40.9  72.3  76.9]
 [203.2 214.8 219.8]]

Final Centroids (Part b):
[[ 24.7  49.5  46. ]
 [186.1 197.4 197.9]
 [ 86.6 119.4 128.2]]

Results differ: True


In [ ]:
import numpy as np
from sklearn.cluster import KMeans

# Step 1: Define the 16 colors (RGB values)
colors = {
    1: (85, 27, 3),
    2: (168, 198, 217),
    3: (68, 115, 141),
    4: (42, 110, 4),
    5: (187, 186, 166),
    6: (239, 239, 243),
    7: (138, 170, 192),
    8: (57, 77, 67),
    9: (107, 145, 165),
    10: (191, 212, 227),
    11: (30, 48, 34),
    12: (139, 144, 122),
    13: (215, 210, 192),
    14: (165, 167, 148),
    15: (28, 85, 119),
    16: (91, 108, 94)
}

# Convert colors to numpy array and normalize (0-1)
X = np.array(list(colors.values())) / 255.0

# Part (a): Initial centroids 5, 9, 13
initial_centroids_a = np.array([colors[5], colors[9], colors[13]]) / 255.0
kmeans_a = KMeans(n_clusters=3, init=initial_centroids_a, n_init=1, max_iter=1000)
kmeans_a.fit(X)
final_centroids_a = kmeans_a.cluster_centers_ * 255

# Part (b): Initial centroids 1, 2, 3
initial_centroids_b = np.array([colors[1], colors[2], colors[3]]) / 255.0
kmeans_b = KMeans(n_clusters=3, init=initial_centroids_b, n_init=1, max_iter=1000)
kmeans_b.fit(X)
final_centroids_b = kmeans_b.cluster_centers_ * 255

# Print results
print("Final Centroids (Part a):")
print(np.round(final_centroids_a, 1))
print("\nFinal Centroids (Part b):")
print(np.round(final_centroids_b, 1))
print("\nResults differ:", not np.allclose(final_centroids_a, final_centroids_b))

Final Centroids (Part a):
[[179.4 178.5 157.9]
 [ 84.2  27.2   3. ]
 [213.3 208.5 190.6]]

Final Centroids (Part b):
[[167.8 197.8 216.8]
 [ 84.3  27.2   3. ]
 [213.3 208.5 190.6]]

Results differ: True

In [ ]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr, kendalltau

# Step 1: Load data
data = {
    'Car Age': [5, 3, 8, 2, 6, 4, 7, 1, 9],
    'Distance Driven': [50, 30, 80, 20, 60, 40, 70, 10, 90],
    'Previous Owners': [1, 2, 3, 1, 2, 1, 3, 1, 4],
    'Price': [20, 25, 15, 30, 18, 22, 16, 35, 12]
}
df = pd.DataFrame(data)

# Part (a): Pearson correlation between Distance Driven and Previous Owners
corr, p_value = pearsonr(df['Distance Driven'], df['Previous Owners'])
print(f"Pearson Correlation (Distance vs Owners): {corr:.4f} (p-value: {p_value:.4f})")

# Part (b): Spearman correlation for predictors of Price
spearman_age, _ = spearmanr(df['Car Age'], df['Price'])
spearman_owners, _ = spearmanr(df['Previous Owners'], df['Price'])
print(f"\nSpearman Correlation (Age vs Price): {spearman_age:.4f}")
print(f"Spearman Correlation (Owners vs Price): {spearman_owners:.4f}")

# Part (c): Kendall's Tau between Distance Driven and Price
tau, _ = kendalltau(df['Distance Driven'], df['Price'])
print(f"\nKendall's Tau (Distance vs Price): {tau:.4f}")

In [ ]:
# Pearson Correlation (Distance vs Owners): 0.7633 (p-value: 0.0153)

# Spearman Correlation (Age vs Price): -0.9167
# Spearman Correlation (Owners vs Price): -0.8000

# Kendall's Tau (Distance vs Price): -0.7143