Q1 (a)
Iteration 1 - clustering:
Cluster 0 color indexes: [5, 14]
Cluster 1 color indexes: [1, 3, 4, 7, 8, 9, 11, 12, 15, 16]
Cluster 2 color indexes: [2, 6, 10, 13]

Iteration 1 - new centroids:
Cluster 0 center: (176.0, 176.5, 157.0)
Cluster 1 center: (67.0, 96.5, 101.7)
Cluster 2 center: (203.2, 214.8, 219.8)

Iteration 2 - clustering:
Cluster 0 color indexes: [5, 8, 9, 12, 14]
Cluster 1 color indexes: [1, 3, 4, 7, 11, 15, 16]
Cluster 2 color indexes: [2, 6, 10, 13]

Iteration 2 - new centroids:
Cluster 0 center: (147.2, 162.4, 158.6)
Cluster 1 center: (40.9, 72.3, 76.9)
Cluster 2 center: (203.2, 214.8, 219.8)

Iteration 3 - clustering:
Cluster 0 color indexes: [5, 8, 9, 12, 14]
Cluster 1 color indexes: [1, 3, 4, 7, 11, 15, 16]
Cluster 2 color indexes: [2, 6, 10, 13]

Final clustering result:
Cluster 0 ((147.2, 162.4, 158.6)): [5, 8, 9, 12, 14]
Cluster 1 ((40.9, 72.3, 76.9)): [1, 3, 4, 7, 11, 15, 16]
Cluster 2 ((203.2, 214.8, 219.8)): [2, 6, 10, 13]

Q1 (b)

Iteration 1 - clustering:
Cluster 0 color indexes: [1, 4, 7, 11]
Cluster 1 color indexes: [2, 5, 6, 8, 10, 13, 14]
Cluster 2 color indexes: [3, 9, 12, 15, 16]

Iteration 1 - new centroids:
Cluster 0 中心: (24.8, 49.5, 46.0)
Cluster 1 中心: (186.1, 197.4, 197.9)
Cluster 2 中心: (86.6, 119.4, 128.2)

Iteration 2 - clustering:
Cluster 0 color indexes: [1, 4, 7, 11]
Cluster 1 color indexes: [2, 5, 6, 8, 10, 13, 14]
Cluster 2 color indexes: [3, 9, 12, 15, 16]

Final clustering result:
Cluster 0 ((24.8, 49.5, 46.0)): [1, 4, 7, 11]
Cluster 1 ((186.1, 197.4, 197.9)): [2, 5, 6, 8, 10, 13, 14]
Cluster 2 ((86.6, 119.4, 128.2)): [3, 9, 12, 15, 16]

poe:
Final Centroids (RGB values):
Centroid 1: (147.2, 162.4, 158.6)
Centroid 2: (40.9, 72.3, 76.9)
Centroid 3: (203.2, 214.8, 219.8)
Final Centroids (RGB values):
Centroid 1: (24.8, 49.5, 46.0)
Centroid 2: (186.1, 197.4, 197.9)
Centroid 3: (86.6, 119.4, 128.2)

In [ ]:
# wenxiaobai

In [2]:
colors = {
    1: (8, 52, 73),
    2: (168, 198, 217),
    3: (68, 115, 141),
    4: (4, 21, 10),
    5: (187, 186, 166),
    6: (239, 239, 243),
    7: (57, 77, 67),
    8: (138, 170, 192),
    9: (107, 145, 165),
    10: (191, 212, 227),
    11: (30, 48, 34),
    12: (139, 144, 122),
    13: (215, 210, 192),
    14: (165, 167, 148),
    15: (28, 85, 119),
    16: (91, 108, 94)
}

# 初始中心点（索引5,9,13对应的颜色）
centroids = [
    (187, 186, 166),  # Cluster 0 (初始索引5)
    (107, 145, 165),  # Cluster 1 (初始索引9)
    (215, 210, 192)   # Cluster 2 (初始索引13)
]

max_iterations = 10
converged = False

for iter in range(max_iterations):
    # 步骤1：分配颜色到最近的簇
    clusters = {0: [], 1: [], 2: []}
    
    for idx, rgb in colors.items():
        # 计算到每个中心的欧氏距离
        distances = [
            sum((a - b)**2 for a, b in zip(rgb, centroids[0]))**0.5,
            sum((a - b)**2 for a, b in zip(rgb, centroids[1]))**0.5,
            sum((a - b)**2 for a, b in zip(rgb, centroids[2]))**0.5
        ]
        # 找到最近簇
        closest_cluster = distances.index(min(distances))
        clusters[closest_cluster].append(idx)
    
    # 输出当前分配结果
    print(f"\nIteration {iter+1} - clustering:")
    for cluster, members in clusters.items():
        print(f"Cluster {cluster} color indexes: {sorted(members)}")
    
    # 步骤2：计算新中心点
    new_centroids = []
    for cluster in [0, 1, 2]:
        if clusters[cluster]:
            # 计算RGB分量平均值
            avg_r = sum(colors[idx][0] for idx in clusters[cluster]) / len(clusters[cluster])
            avg_g = sum(colors[idx][1] for idx in clusters[cluster]) / len(clusters[cluster])
            avg_b = sum(colors[idx][2] for idx in clusters[cluster]) / len(clusters[cluster])
            new_centroids.append((round(avg_r, 1), round(avg_g, 1), round(avg_b, 1)))
        else:
            # 空簇保持原中心（根据K-means变体处理方式）
            new_centroids.append(centroids[cluster])
    
    # 检查是否收敛
    if new_centroids == centroids:
        converged = True
        break
    
    # 输出当前中心点
    print(f"\nIteration {iter+1} - new centroids:")
    for i, centroid in enumerate(new_centroids):
        print(f"Cluster {i} center: {centroid}")
    
    centroids = new_centroids

# 最终结果输出
print("\nFinal clustering result:" if converged else "\n达到最大迭代次数")
for cluster, members in clusters.items():
    print(f"Cluster {cluster} ({centroids[cluster]}): {sorted(members)}")


Iteration 1 - clustering:
Cluster 0 color indexes: [5, 14]
Cluster 1 color indexes: [1, 3, 4, 7, 8, 9, 11, 12, 15, 16]
Cluster 2 color indexes: [2, 6, 10, 13]

Iteration 1 - new centroids:
Cluster 0 center: (176.0, 176.5, 157.0)
Cluster 1 center: (67.0, 96.5, 101.7)
Cluster 2 center: (203.2, 214.8, 219.8)

Iteration 2 - clustering:
Cluster 0 color indexes: [5, 8, 9, 12, 14]
Cluster 1 color indexes: [1, 3, 4, 7, 11, 15, 16]
Cluster 2 color indexes: [2, 6, 10, 13]

Iteration 2 - new centroids:
Cluster 0 center: (147.2, 162.4, 158.6)
Cluster 1 center: (40.9, 72.3, 76.9)
Cluster 2 center: (203.2, 214.8, 219.8)

Iteration 3 - clustering:
Cluster 0 color indexes: [5, 8, 9, 12, 14]
Cluster 1 color indexes: [1, 3, 4, 7, 11, 15, 16]
Cluster 2 color indexes: [2, 6, 10, 13]

Final clustering result:
Cluster 0 ((147.2, 162.4, 158.6)): [5, 8, 9, 12, 14]
Cluster 1 ((40.9, 72.3, 76.9)): [1, 3, 4, 7, 11, 15, 16]
Cluster 2 ((203.2, 214.8, 219.8)): [2, 6, 10, 13]


In [7]:
colors = {
    1: (8, 52, 73),
    2: (168, 198, 217),
    3: (68, 115, 141),
    4: (4, 21, 10),
    5: (187, 186, 166),
    6: (239, 239, 243),
    7: (57, 77, 67),
    8: (138, 170, 192),
    9: (107, 145, 165),
    10: (191, 212, 227),
    11: (30, 48, 34),
    12: (139, 144, 122),
    13: (215, 210, 192),
    14: (165, 167, 148),
    15: (28, 85, 119),
    16: (91, 108, 94)
}

# 修改后的初始中心点（索引1,2,3对应的颜色）
centroids = [
    (8, 52, 73),    # Cluster 0 (初始索引1)
    (168, 198, 217),# Cluster 1 (初始索引2)
    (68, 115, 141)  # Cluster 2 (初始索引3)
]

max_iterations = 10
converged = False

for iter in range(max_iterations):
    clusters = {0: [], 1: [], 2: []}
    
    # 分配颜色到最近的簇
    for idx, rgb in colors.items():
        distances = [
            sum((a - b)**2 for a, b in zip(rgb, centroids[0]))**0.5,
            sum((a - b)**2 for a, b in zip(rgb, centroids[1]))**0.5,
            sum((a - b)**2 for a, b in zip(rgb, centroids[2]))**0.5
        ]
        closest_cluster = distances.index(min(distances))
        clusters[closest_cluster].append(idx)
    
    print(f"\nIteration {iter+1} - clustering:")
    for cluster, members in clusters.items():
        print(f"Cluster {cluster} color indexes: {sorted(members)}")
    
    # 计算新中心点
    new_centroids = []
    for cluster in [0, 1, 2]:
        if clusters[cluster]:
            avg_r = sum(colors[idx][0] for idx in clusters[cluster])/len(clusters[cluster])
            avg_g = sum(colors[idx][1] for idx in clusters[cluster])/len(clusters[cluster])
            avg_b = sum(colors[idx][2] for idx in clusters[cluster])/len(clusters[cluster])
            new_centroids.append((round(avg_r,1), round(avg_g,1), round(avg_b,1)))
        else:
            new_centroids.append(centroids[cluster])
    
    # 收敛检查
    if new_centroids == centroids:
        converged = True
        break
        
    print(f"\nIteration {iter+1} - new centroids:")
    for i, centroid in enumerate(new_centroids):
        print(f"Cluster {i} centroids: {centroid}")
    
    centroids = new_centroids

# 最终结果对比
print("\nFinal clustering result:" if converged else "\n达到最大迭代次数")
for cluster, members in clusters.items():
    print(f"Cluster {cluster} ({centroids[cluster]}): {sorted(members)}")


Iteration 1 - clustering:
Cluster 0 color indexes: [1, 4, 7, 11]
Cluster 1 color indexes: [2, 5, 6, 8, 10, 13, 14]
Cluster 2 color indexes: [3, 9, 12, 15, 16]

Iteration 1 - new centroids:
Cluster 0 中心: (24.8, 49.5, 46.0)
Cluster 1 中心: (186.1, 197.4, 197.9)
Cluster 2 中心: (86.6, 119.4, 128.2)

Iteration 2 - clustering:
Cluster 0 color indexes: [1, 4, 7, 11]
Cluster 1 color indexes: [2, 5, 6, 8, 10, 13, 14]
Cluster 2 color indexes: [3, 9, 12, 15, 16]

Final clustering result:
Cluster 0 ((24.8, 49.5, 46.0)): [1, 4, 7, 11]
Cluster 1 ((186.1, 197.4, 197.9)): [2, 5, 6, 8, 10, 13, 14]
Cluster 2 ((86.6, 119.4, 128.2)): [3, 9, 12, 15, 16]


In [ ]:
# poe

In [6]:
import numpy as np
from sklearn.cluster import KMeans

# Define the colors as an array of RGB values
colors = np.array([
    (8, 52, 73),
    (168, 198, 217),
    (68, 115, 141),
    (4, 21, 10),
    (187, 186, 166),
    (239, 239, 243),
    (57, 77, 67),
    (138, 170, 192),
    (107, 145, 165),
    (191, 212, 227),
    (30, 48, 34),
    (139, 144, 122),
    (215, 210, 192),
    (165, 167, 148),
    (28, 85, 119),
    (91, 108, 94)
])



# Initialize KMeans with 3 clusters
kmeans = KMeans(n_clusters=3, init=np.array([
    (187, 186, 166),  # Centroid 1 (Color 5)
    (107, 145, 165),  # Centroid 2 (Color 9)
    (215, 210, 192)   # Centroid 3 (Color 13)
]), n_init=1, max_iter=100)

kmeans2 = KMeans(n_clusters=3, init=np.array([
    (8, 52, 73),    # Cluster 0 (初始索引1)
    (168, 198, 217),# Cluster 1 (初始索引2)
    (68, 115, 141)  # Cluster 2 (初始索引3)
]), n_init=1, max_iter=100)

# Fit the model to the color data
kmeans.fit(colors)
kmeans2.fit(colors)

# Get the cluster centers (final centroids)
centroids = kmeans.cluster_centers_

# Print the results
print("Final Centroids (RGB values):")
for i, centroid in enumerate(centroids, start=1):
    print(f"Centroid {i}: ({centroid[0]:.1f}, {centroid[1]:.1f}, {centroid[2]:.1f})")

centroids2 = kmeans2.cluster_centers_
print("Final Centroids (RGB values):")
for i, centroid in enumerate(centroids2, start=1):
    print(f"Centroid {i}: ({centroid[0]:.1f}, {centroid[1]:.1f}, {centroid[2]:.1f})")

Final Centroids (RGB values):
Centroid 1: (147.2, 162.4, 158.6)
Centroid 2: (40.9, 72.3, 76.9)
Centroid 3: (203.2, 214.8, 219.8)
Final Centroids (RGB values):
Centroid 1: (24.8, 49.5, 46.0)
Centroid 2: (186.1, 197.4, 197.9)
Centroid 3: (86.6, 119.4, 128.2)


In [ ]:
# doubao

In [14]:
import numpy as np
from sklearn.cluster import KMeans

# Step 1: Define the 16 colors (RGB values)
colors = {
    1: (8, 52, 73),
    2: (168, 198, 217),
    3: (68, 115, 141),
    4: (4, 21, 10),
    5: (187, 186, 166),
    6: (239, 239, 243),
    7: (57, 77, 67),
    8: (138, 170, 192),
    9: (107, 145, 165),
    10: (191, 212, 227),
    11: (30, 48, 34),
    12: (139, 144, 122),
    13: (215, 210, 192),
    14: (165, 167, 148),
    15: (28, 85, 119),
    16: (91, 108, 94)
}

# Convert colors to numpy array and normalize (0-1)
X = np.array(list(colors.values())) / 255.0

# Part (a): Initial centroids 5, 9, 13
initial_centroids_a = np.array([colors[5], colors[9], colors[13]]) / 255.0
kmeans_a = KMeans(n_clusters=3, init=initial_centroids_a, n_init=1, max_iter=1000)
kmeans_a.fit(X)
final_centroids_a = kmeans_a.cluster_centers_ * 255

# Part (b): Initial centroids 1, 2, 3
initial_centroids_b = np.array([colors[1], colors[2], colors[3]]) / 255.0
kmeans_b = KMeans(n_clusters=3, init=initial_centroids_b, n_init=1, max_iter=1000)
kmeans_b.fit(X)
final_centroids_b = kmeans_b.cluster_centers_ * 255

# Print results
print("Final Centroids (Part a):")
print(np.round(final_centroids_a, 1))
print("\nFinal Centroids (Part b):")
print(np.round(final_centroids_b, 1))
print("\nResults differ:", not np.allclose(final_centroids_a, final_centroids_b))

Final Centroids (Part a):
[[147.2 162.4 158.6]
 [ 40.9  72.3  76.9]
 [203.2 214.8 219.8]]

Final Centroids (Part b):
[[ 24.7  49.5  46. ]
 [186.1 197.4 197.9]
 [ 86.6 119.4 128.2]]

Results differ: True


In [9]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr, kendalltau

# Step 1: Load data
data = {
    'Car Age': [5, 3, 8, 2, 6, 4, 7, 1, 9],
    'Distance Driven': [50, 30, 80, 20, 60, 40, 70, 10, 90],
    'Previous Owners': [1, 2, 3, 1, 2, 1, 3, 1, 4],
    'Price': [20, 25, 15, 30, 18, 22, 16, 35, 12]
}
df = pd.DataFrame(data)

# Part (a): Pearson correlation between Distance Driven and Previous Owners
corr, p_value = pearsonr(df['Distance Driven'], df['Previous Owners'])
print(f"Pearson Correlation (Distance vs Owners): {corr:.4f} (p-value: {p_value:.4f})")

# Part (b): Spearman correlation for predictors of Price
spearman_age, _ = spearmanr(df['Car Age'], df['Price'])
spearman_owners, _ = spearmanr(df['Previous Owners'], df['Price'])
print(f"\nSpearman Correlation (Age vs Price): {spearman_age:.4f}")
print(f"Spearman Correlation (Owners vs Price): {spearman_owners:.4f}")

# Part (c): Kendall's Tau between Distance Driven and Price
tau, _ = kendalltau(df['Distance Driven'], df['Price'])
print(f"\nKendall's Tau (Distance vs Price): {tau:.4f}")

Pearson Correlation (Distance vs Owners): 0.8573 (p-value: 0.0031)

Spearman Correlation (Age vs Price): -1.0000
Spearman Correlation (Owners vs Price): -0.8433

Kendall's Tau (Distance vs Price): -1.0000


In [10]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr, kendalltau

# Define the dataset
data = {
    'Car Age': [5, 3, 8, 2, 6, 4, 7, 1, 9],
    'Distance Driven': [50, 30, 80, 20, 60, 40, 70, 10, 90],
    'Previous Owners': [1, 2, 3, 1, 2, 1, 3, 1, 4],
    'Price': [20, 25, 15, 30, 18, 22, 16, 35, 12]
}

# Create a DataFrame
df = pd.DataFrame(data)

# 1. Pearson correlation between Distance Driven and Previous Owners
pearson_corr, _ = pearsonr(df['Distance Driven'], df['Previous Owners'])
print(f"Pearson Correlation between Distance Driven and Previous Owners: {pearson_corr:.3f}")

# 2. Spearman Rank correlation to compare Car Age and Previous Owners with Price
spearman_corr_age, _ = spearmanr(df['Car Age'], df['Price'])
spearman_corr_owners, _ = spearmanr(df['Previous Owners'], df['Price'])

print(f"Spearman Rank Correlation between Car Age and Price: {spearman_corr_age:.3f}")
print(f"Spearman Rank Correlation between Previous Owners and Price: {spearman_corr_owners:.3f}")

# Determine the better predictor
if abs(spearman_corr_age) > abs(spearman_corr_owners):
    print("Car Age is a better predictor of Price.")
else:
    print("Number of Previous Owners is a better predictor of Price.")

# 3. Kendall's Tau between Distance Driven and Price
kendall_tau, _ = kendalltau(df['Distance Driven'], df['Price'])
print(f"Kendall's Tau between Distance Driven and Price: {kendall_tau:.3f}")

Pearson Correlation between Distance Driven and Previous Owners: 0.857
Spearman Rank Correlation between Car Age and Price: -1.000
Spearman Rank Correlation between Previous Owners and Price: -0.843
Car Age is a better predictor of Price.
Kendall's Tau between Distance Driven and Price: -1.000


In [11]:
# wenxiaobai

In [21]:
import pandas as pd

data = {
    'Car Age': [5, 3, 8, 2, 6, 4, 7, 1, 9],
    'Previous Owners': [1, 2, 3, 1, 2, 1, 3, 1, 4],
    'Price': [20, 25, 15, 30, 18, 22, 16, 35, 12]
}

def calculate_spearman(x, y):
    # 计算秩次（处理重复值）
    x_rank = x.rank(method='average')
    y_rank = y.rank(method='average')
    
    # 计算秩差平方和
    d_sq = (x_rank - y_rank)**2
    sum_d_sq = d_sq.sum()
    
    # 斯皮尔曼系数公式
    n = len(x)
    rho = 1 - (6 * sum_d_sq) / (n * (n**2 - 1))
    return rho

# 提取数据
car_age = pd.Series(data['Car Age'])
owners = pd.Series(data['Previous Owners'])
price = pd.Series(data['Price'])

# 验证秩次计算
owners_rank = owners.rank(method='average').round(2)
price_rank = price.rank(ascending=False, method='average').round(2)  # Price是价格越高排名越低

print("Previous Owners 秩次:", list(owners_rank))
print("Price 秩次:", list(price_rank))

# 计算相关系数
car_age_price = calculate_spearman(car_age, price)
owners_price = calculate_spearman(owners, price)

print(f"\nCar Age-Price Spearman ρ: {car_age_price:.3f}")
print(f"Previous Owners-Price Spearman ρ: {owners_price:.3f}")

Previous Owners 秩次: [2.5, 5.5, 7.5, 2.5, 5.5, 2.5, 7.5, 2.5, 9.0]
Price 秩次: [5.0, 3.0, 8.0, 2.0, 6.0, 4.0, 7.0, 1.0, 9.0]

Car Age-Price Spearman ρ: -1.000
Previous Owners-Price Spearman ρ: -0.750


In [22]:


data = {
    'Car Age': [5, 3, 8, 2, 6, 4, 7, 1, 9],
    'Previous Owners': [1, 2, 3, 1, 2, 1, 3, 1, 4],
    'Price': [20, 25, 15, 30, 18, 22, 16, 35, 12]
}

def compute_ranks(values):
    """Calculate ranks with proper tie handling"""
    sorted_pairs = sorted((val, idx) for idx, val in enumerate(values))
    ranks = [0.0] * len(values)
    n = len(values)
    i = 0
    
    while i < n:
        j = i
        while j < n and sorted_pairs[j][0] == sorted_pairs[i][0]:
            j += 1
        avg_rank = (i + 1 + j) / 2.0  # 1-based indexing
        for k in range(i, j):
            original_idx = sorted_pairs[k][1]
            ranks[original_idx] = avg_rank
        i = j
    return ranks

def print_analysis(x, y, x_name, y_name):
    """Perform full Spearman analysis with detailed output"""
    # Get ranks
    x_rank = compute_ranks(x)
    y_rank = compute_ranks(y)
    
    print(f"\n{'='*60}")
    print(f"Analysis of {x_name} vs {y_name}")
    print(f"{'='*60}")
    
    # Print raw data
    print("\nOriginal Data:")
    print(f"{x_name:>15} | {y_name:>15}")
    print("-"*35)
    for a, b in zip(x, y):
        print(f"{a:15} | {b:15}")
    
    # Print ranks
    print("\nRanks with Tie Handling:")
    print(f"{x_name+' Rank':>15} | {y_name+' Rank':>15} | {'Difference (d)':>15} | {'d²':>15}")
    print("-"*75)
    d_squared_total = 0
    for i in range(len(x)):
        d = x_rank[i] - y_rank[i]
        d_sq = d ** 2
        d_squared_total += d_sq
        print(f"{x_rank[i]:15.2f} | {y_rank[i]:15.2f} | {d:15.2f} | {d_sq:15.2f}")
    
    # Calculate Spearman's rho
    n = len(x)
    numerator = 6 * d_squared_total
    denominator = n * (n**2 - 1)
    rho = 1 - numerator/denominator
    
    print("\nIntermediate Calculations:")
    print(f"Sum of d² (Σd²) = {d_squared_total:.2f}")
    print(f"n(n² - 1) = {n}*({n}²-1) = {denominator}")
    print(f"Spearman's ρ = 1 - (6*{d_squared_total:.2f})/{denominator} = {rho:.3f}")
    
    return rho

# Perform analyses
print("STARTING ANALYSIS...")
car_age_rho = print_analysis(data['Car Age'], data['Price'], "Car Age", "Price")
owners_rho = print_analysis(data['Previous Owners'], data['Price'], "Previous Owners", "Price")

# Final conclusion
print("\n\nFINAL CONCLUSION:")
print(f"{'Car Age vs Price Correlation:':<35} ρ = {car_age_rho:.3f}")
print(f"{'Previous Owners vs Price Correlation:':<35} ρ = {owners_rho:.3f}")

if abs(car_age_rho) > abs(owners_rho):
    conclusion = ("Car Age is the stronger predictor of Price. There is a perfect negative correlation "
                  "(ρ = -1.0), meaning car price decreases consistently as vehicles get older.")
else:
    conclusion = ("Previous Owners is the stronger predictor of Price. There is a strong negative correlation "
                  "(ρ = -0.750), meaning prices tend to decrease with more previous owners, but not perfectly.")

print(f"\n{conclusion}")
print("Note: Negative correlation means as the predictor increases, price decreases")

STARTING ANALYSIS...

Analysis of Car Age vs Price

Original Data:
        Car Age |           Price
-----------------------------------
              5 |              20
              3 |              25
              8 |              15
              2 |              30
              6 |              18
              4 |              22
              7 |              16
              1 |              35
              9 |              12

Ranks with Tie Handling:
   Car Age Rank |      Price Rank |  Difference (d) |              d²
---------------------------------------------------------------------------
           5.00 |            5.00 |            0.00 |            0.00
           3.00 |            7.00 |           -4.00 |           16.00
           8.00 |            2.00 |            6.00 |           36.00
           2.00 |            8.00 |           -6.00 |           36.00
           6.00 |            4.00 |            2.00 |            4.00
           4.00 |            6.00 |

In [24]:
# Dataset
data = {
    'Car Age': [5, 3, 8, 2, 6, 4, 7, 1, 9],
    'Previous Owners': [1, 2, 3, 1, 2, 1, 3, 1, 4],
    'Distance Driven': [50, 30, 80, 20, 60, 40, 70, 10, 90],
    'Price': [20, 25, 15, 30, 18, 22, 16, 35, 12]
}

def rank_data(arr):
    """Calculate ranks with tie handling using average ranking"""
    sorted_arr = sorted((val, idx) for idx, val in enumerate(arr))
    ranks = [0] * len(arr)
    
    print("\nRanking Process:")
    for i, (val, idx) in enumerate(sorted_arr):
        # Find all elements with same value
        duplicates = [j for j, (v, _) in enumerate(sorted_arr) if v == val]
        avg_rank = sum(duplicates)/len(duplicates) + 1  # +1 for 1-based indexing
        for j in duplicates:
            ranks[sorted_arr[j][1]] = avg_rank
        print(f"Value {val} at positions {[sorted_arr[d][1] for d in duplicates]} gets rank {avg_rank:.1f}")
    
    return ranks

def spearman_rank(x, y, x_name, y_name):
    """Calculate Spearman's rank correlation coefficient with detailed output"""
    print(f"\n{'='*40}\nCalculating Spearman for {x_name} vs {y_name}\n{'='*40}")
    
    # Step 1: Rank the data
    x_rank = rank_data(x)
    y_rank = rank_data(y)
    
    print(f"\n{x_name} Ranks: {[round(r,1) for r in x_rank]}")
    print(f"{y_name} Ranks: {[round(r,1) for r in y_rank]}")
    
    # Step 2: Calculate differences
    d = [xr - yr for xr, yr in zip(x_rank, y_rank)]
    d_sq = [di**2 for di in d]
    
    print("\nPair Calculations:")
    print(f"{'Index':<5} | {x_name:<7} | {y_name:<7} | {'d':<6} | {'d²':<6}")
    print("-"*40)
    for i in range(len(x)):
        print(f"{i+1:<5} | {x_rank[i]:<7.1f} | {y_rank[i]:<7.1f} | {d[i]:<6.1f} | {d_sq[i]:<6.1f}")
    
    # Step 3: Calculate components
    sum_d_sq = sum(d_sq)
    n = len(x)
    numerator = 6 * sum_d_sq
    denominator = n * (n**2 - 1)
    rho = 1 - numerator/denominator
    
    print("\nFinal Calculation:")
    print(f"Σd² = {sum_d_sq}")
    print(f"n(n²-1) = {n}*({n}²-1) = {denominator}")
    print(f"rho = 1 - (6*{sum_d_sq})/{denominator} = {rho:.3f}")
    
    return rho

def kendalls_tau(x, y, x_name, y_name):
    """Calculate Kendall's Tau with detailed pair analysis"""
    print(f"\n{'='*40}\nCalculating Kendall's Tau for {x_name} vs {y_name}\n{'='*40}")
    
    n = len(x)
    pairs = []
    C = 0  # Concordant pairs
    D = 0  # Discordant pairs
    
    print("\nPair-wise Analysis:")
    for i in range(n):
        for j in range(i+1, n):
            x_dir = x[i] - x[j]
            y_dir = y[i] - y[j]
            
            if x_dir * y_dir > 0:
                pairs.append(('C', i+1, j+1))
                C += 1
            elif x_dir * y_dir < 0:
                pairs.append(('D', i+1, j+1))
                D += 1
            else:
                pairs.append(('T', i+1, j+1))
    
    # Print first 5 pairs for demonstration
    for p in pairs[:5]:
        print(f"Pair ({p[1]},{p[2]}): {p[0]}")
    print(f"... Total {len(pairs)} pairs analyzed")
    
    total_pairs = n*(n-1)/2
    tau = (C - D) / total_pairs
    
    print("\nCount Summary:")
    print(f"Concordant pairs (C): {C}")
    print(f"Discordant pairs (D): {D}")
    print(f"Total pairs: {total_pairs}")
    print(f"Kendall's Tau = (C-D)/Total = ({C}-{D})/{total_pairs} = {tau:.3f}")
    
    return tau

# # Problem 1: Compare Car Age vs Price and Previous Owners vs Price
# print("="*60)
# print("PROBLEM 1: Predictor Comparison using Spearman")
# print("="*60)

# # Car Age vs Price
# car_age_price = spearman_rank(data['Car Age'], data['Price'], "Car Age", "Price")

# # Previous Owners vs Price
# owners_price = spearman_rank(data['Previous Owners'], data['Price'], "Previous Owners", "Price")

# print("\nComparison Results:")
# print(f"Car Age vs Price: ρ = {car_age_price:.3f}")
# print(f"Previous Owners vs Price: ρ = {owners_price:.3f}")

# if abs(car_age_price) > abs(owners_price):
#     conclusion = "Car Age is a better predictor of Price"
# else:
#     conclusion = "Previous Owners is a better predictor of Price"

# print(f"\nConclusion: {conclusion} (higher absolute correlation)")

# Problem 2: Kendall's Tau between Distance Driven and Price
print("\n" + "="*60)
print("PROBLEM 2: Kendall's Tau Calculation")
print("="*60)

kendall_result = kendalls_tau(data['Distance Driven'], data['Price'], "Distance Driven", "Price")
print(f"\nFinal Kendall's Tau: τ = {kendall_result:.3f}")


PROBLEM 2: Kendall's Tau Calculation

Calculating Kendall's Tau for Distance Driven vs Price

Pair-wise Analysis:
Pair (1,2): D
Pair (1,3): D
Pair (1,4): D
Pair (1,5): D
Pair (1,6): D
... Total 36 pairs analyzed

Count Summary:
Concordant pairs (C): 0
Discordant pairs (D): 36
Total pairs: 36.0
Kendall's Tau = (C-D)/Total = (0-36)/36.0 = -1.000

Final Kendall's Tau: τ = -1.000
